# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db18786f98a758200446533777a270888465c43c16d9aae3cd0de9b6c133ec59ca5bd01538e3fc6b4fcc63d66fbe886cdbecf0f69ca04aa1f83651d92d47277

test:
  secret_key_base: 54751b8f7fdeab0cc6576358696529a93b13cdb5f56946bcbd141749c4c160d538a5f52e55235dff281e2e821345853f2a9423c40ee990d1a3a6676159df58ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
